# Jekyll Configuration
title: Fahim Muntasir Moumit
email: fahimmmuntasir040@gmail.com
description: 'Innovative Full Stack Developer Portfolio with a focus on Node.js, Django, Spring Boot, and React. Hosted on GitHub Pages.'
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site
github_username: your_github_username # Replace with your GitHub username
permalink: /blog/:title/

# Theme and Dependencies
remote_theme: pages-themes/minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Customize the links in the header
header_pages:
 - index.html
 - blog.html # You'll need to create this later for a dedicated index

# Blog Post Settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"